import mongoose from 'mongoose';
import config from '../app/config';
import { Legal } from '../app/modules/legal/legal.model';

const BANGLADESHI_LAWS = [
    {
        actName: 'The Penal Code',
        year: '1860',
        number: '302',
        title: 'Punishment for murder',
        chapter: 'XVI',
        chapterTitle: 'Of Offences Affecting the Human Body',
        previewText: 'Whoever commits murder shall be punished with death, or imprisonment for life, and shall also be liable to fine.',
        fullText: 'Whoever commits murder shall be punished with death, or imprisonment for life, and shall also be liable to fine. Murder is the highest form of culpable homicide.',
        subsections: ['Death penalty', 'Life imprisonment', 'Fine'],
        relatedSections: ['299', '300', '304'],
    },
    {
        actName: 'The Penal Code',
        year: '1860',
        number: '378',
        title: 'Theft',
        chapter: 'XVII',
        chapterTitle: 'Of Offences Against Property',
        previewText: 'Whoever, intending to take dishonestly any moveable property out of the possession of any person without that person\'s consent...',
        fullText: 'Whoever, intending to take dishonestly any moveable property out of the possession of any person without that person\'s consent, moves that property in order to such taking, is said to commit theft.',
        subsections: ['Dishonest intention', 'Moveable property', 'Out of possession', 'Without consent'],
        relatedSections: ['379', '380'],
    },
    {
        actName: 'The Penal Code',
        year: '1860',
        number: '323',
        title: 'Punishment for voluntarily causing hurt',
        chapter: 'XVI',
        chapterTitle: 'Of Offences Affecting the Human Body',
        previewText: 'Whoever, except in the case provided for by section 334, voluntarily causes hurt, shall be punished with imprisonment...',
        fullText: 'Whoever, except in the case provided for by section 334, voluntarily causes hurt, shall be punished with imprisonment of either description for a term which may extend to one year, or with fine which may extend to one thousand taka, or with both.',
        subsections: [],
        relatedSections: ['319', '321', '324'],
    },
    {
        actName: 'The Penal Code',
        year: '1860',
        number: '420',
        title: 'Cheating and dishonestly inducing delivery of property',
        chapter: 'XVII',
        chapterTitle: 'Of Offences Against Property',
        previewText: 'Whoever cheats and thereby dishonestly induces the person deceived to deliver any property to any person...',
        fullText: 'Whoever cheats and thereby dishonestly induces the person deceived to deliver any property to any person, or to make, alter or destroy the whole or any part of a valuable security, or anything which is signed or sealed, and which is capable of being converted into a valuable security, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.',
        subsections: [],
        relatedSections: ['415', '417'],
    },
    {
        actName: 'The Penal Code',
        year: '1860',
        number: '499',
        title: 'Defamation',
        chapter: 'XXI',
        chapterTitle: 'Of Defamation',
        previewText: 'Whoever by words either spoken or intended to be read, or by signs or by visible representations, makes or publishes any imputation...',
        fullText: 'Whoever by words either spoken or intended to be read, or by signs or by visible representations, makes or publishes any imputation concerning any person intending to harm, or knowing or having reason to believe that such imputation will harm, the reputation of such person, is said, except in the cases hereinafter excepted, to defame that person.',
        subsections: [],
        relatedSections: ['500'],
    },
    {
        actName: 'The Evidence Act',
        year: '1872',
        number: '3',
        title: 'Interpretation-clause',
        chapter: 'I',
        chapterTitle: 'Preliminary',
        previewText: 'In this Act the following words and expressions are used in the following senses, unless a contrary intention appears from the context...',
        fullText: '“Fact” means and includes— (1) any thing, state of things, or relation of things, capable of being perceived by the senses; (2) any mental condition of which any person is conscious.',
        subsections: ['Court', 'Fact', 'Relevant', 'Evidence', 'Document'],
        relatedSections: ['5'],
    },
    {
        actName: 'The Evidence Act',
        year: '1872',
        number: '45',
        title: 'Opinions of experts',
        chapter: 'II',
        chapterTitle: 'Of the Relevancy of Facts',
        previewText: 'When the Court has to form an opinion upon a point of foreign law, or of science, or art, or as to identity of handwriting...',
        fullText: 'When the Court has to form an opinion upon a point of foreign law, or of science, or art, or as to identity of handwriting or finger impressions, the opinions upon that point of persons specially skilled in such foreign law, science or art, or in questions as to identity of handwriting or finger impressions are relevant facts. Such persons are called experts.',
        subsections: [],
        relatedSections: ['46', '47'],
    },
    {
        actName: 'The Code of Criminal Procedure',
        year: '1898',
        number: '54',
        title: 'When police may arrest without warrant',
        chapter: 'V',
        chapterTitle: 'Of Arrest, Escape and Retaking',
        previewText: 'Any police officer may, without an order from a Magistrate and without a warrant, arrest— first, any person who has been concerned in any cognizable offence...',
        fullText: 'Any police officer may, without an order from a Magistrate and without a warrant, arrest— any person who has been concerned in any cognizable offence or against whom a reasonable complaint has been made or credible information has been received or a reasonable suspicion exists of his having been so concerned.',
        subsections: [],
        relatedSections: ['55', '56'],
    },
    {
        actName: 'The Code of Criminal Procedure',
        year: '1898',
        number: '144',
        title: 'Power to issue order absolute at once in urgent cases of nuisance or apprehended danger',
        chapter: 'XI',
        chapterTitle: 'Temporary Orders in Urgent Cases of Nuisance or Apprehended Danger',
        previewText: 'In cases where, in the opinion of a District Magistrate, or any other Magistrate specially empowered by the Government...',
        fullText: 'In cases where, in the opinion of a District Magistrate, or any other Magistrate specially empowered by the Government in this behalf, there is sufficient ground for proceeding under this section and speedy remedy is desirable...',
        subsections: [],
        relatedSections: ['145'],
    },
    {
        actName: 'The Code of Criminal Procedure',
        year: '1898',
        number: '154',
        title: 'Information in cognizable cases',
        chapter: 'XIV',
        chapterTitle: 'Information to the Police and Their Powers to Investigate',
        previewText: 'Every information relating to the commission of a cognizable offence, if given orally to an officer in charge of a police-station...',
        fullText: 'Every information relating to the commission of a cognizable offence, if given orally to an officer in charge of a police-station, shall be reduced to writing by him or under his direction, and be read over to the informant; and every such information, whether given in writing or reduced to writing as aforesaid, shall be signed by the person giving it, and the substance thereof shall be entered in a book to be kept by such officer in such form as the Government may prescribe in this behalf.',
        subsections: [],
        relatedSections: ['155', '156'],
    },
    {
        actName: 'The Code of Civil Procedure',
        year: '1908',
        number: '9',
        title: 'Courts to try all civil suits unless barred',
        chapter: 'I',
        chapterTitle: 'Suits in General',
        previewText: 'The Courts shall (subject to the provisions herein contained) have jurisdiction to try all suits of a civil nature excepting suits of which their cognizance is either expressly or impliedly barred.',
        fullText: 'The Courts shall (subject to the provisions herein contained) have jurisdiction to try all suits of a civil nature excepting suits of which their cognizance is either expressly or impliedly barred.\n\nExplanation.—A suit in which the right to property or to an office is contested is a suit of a civil nature, notwithstanding that such right may depend entirely on the decision of questions as to religious rites or ceremonies.',
        subsections: [],
        relatedSections: ['10', '11'],
    },
    {
        actName: 'The Code of Civil Procedure',
        year: '1908',
        number: '11',
        title: 'Res judicata',
        chapter: 'I',
        chapterTitle: 'Suits in General',
        previewText: 'No Court shall try any suit or issue in which the matter directly and substantially in issue has been directly and substantially in issue in a former suit...',
        fullText: 'No Court shall try any suit or issue in which the matter directly and substantially in issue has been directly and substantially in issue in a former suit between the same parties, or between parties under whom they or any of them claim, litigating under the same title, in a Court competent to try such subsequent suit or the suit in which such issue has been subsequently raised, and has been heard and finally decided by such Court.',
        subsections: [],
        relatedSections: ['10'],
    },
    {
        actName: 'Information and Communication Technology Act',
        year: '2006',
        number: '57',
        title: 'Punishment for publishing fake, obscene or defaming information in electronic form',
        chapter: 'VIII',
        chapterTitle: 'Offences and Penalties',
        previewText: 'If any person deliberately publishes or transmits or causes to be published or transmitted in the website or in any other electronic form any material which is fake and obscene...',
        fullText: 'If any person deliberately publishes or transmits or causes to be published or transmitted in the website or in any other electronic form any material which is fake and obscene or its effect is such as to tend to deprave and corrupt persons who are likely, having regard to all relevant circumstances, to read, see or hear the matter contained or embodied in it, or which causes to be prejudiced the image of the State or person or causes to mislead or defame the person or organization or create possibility to deteriorate law and order, prejudice the image of the State or person or instigate to advertise against any person or organization, then this activity of his will be regarded as an offence.',
        subsections: [],
        relatedSections: ['54', '56'],
    },
    {
        actName: 'The Specific Relief Act',
        year: '1877',
        number: '12',
        title: 'Cases in which specific performance enforceable',
        chapter: 'II',
        chapterTitle: 'Of the Specific Performance of Contracts',
        previewText: 'Except as otherwise provided in this Chapter, the specific performance of any contract may in the discretion of the Court be enforced...',
        fullText: 'Except as otherwise provided in this Chapter, the specific performance of any contract may in the discretion of the Court be enforced— (a) when the act agreed to be done is in the performance wholly or partly of a trust; (b) when there exists no standard for ascertaining the actual damage caused by the non-performance of the act agreed to be done; (c) when the act agreed to be done is such that pecuniary compensation for its non-performance would not afford adequate relief; or (d) when it is probable that pecuniary compensation cannot be got for the non-performance of the act agreed to be done.',
        subsections: [],
        relatedSections: ['21'],
    },
    {
        actName: 'The Contract Act',
        year: '1872',
        number: '2',
        title: 'Interpretation-clause',
        chapter: 'I',
        chapterTitle: 'Preliminary',
        previewText: 'In this Act the following words and expressions are used in the following senses, unless a contrary intention appears from the context...',
        fullText: '(a) When one person signifies to another his willingness to do or to abstain from doing anything, with a view to obtaining the assent of that other to such act or abstinence, he is said to make a proposal.',
        subsections: ['Proposal', 'Promise', 'Consideration', 'Agreement', 'Contract'],
        relatedSections: ['10'],
    },
    {
        actName: 'The Contract Act',
        year: '1872',
        number: '10',
        title: 'What agreements are contracts',
        chapter: 'II',
        chapterTitle: 'Of Contracts, Voidable Contracts and Void Agreements',
        previewText: 'All agreements are contracts if they are made by the free consent of parties competent to contract, for a lawful consideration and with a lawful object...',
        fullText: 'All agreements are contracts if they are made by the free consent of parties competent to contract, for a lawful consideration and with a lawful object, and are not hereby expressly declared to be void.',
        subsections: [],
        relatedSections: ['11', '13', '14'],
    },
    {
        actName: 'The Transfer of Property Act',
        year: '1882',
        number: '54',
        title: '“Sale” defined',
        chapter: 'III',
        chapterTitle: 'Of Sales of Immoveable Property',
        previewText: '“Sale” is a transfer of ownership in exchange for a price paid or promised or part-paid and part-promised.',
        fullText: '“Sale” is a transfer of ownership in exchange for a price paid or promised or part-paid and part-promised. Such transfer, in the case of tangible immoveable property of the value of one hundred taka and upwards, or in the case of a reversion or other intangible thing, can be made only by a registered instrument.',
        subsections: [],
        relatedSections: ['55'],
    },
    {
        actName: 'The Nari-O-Shishu Nirjatan Daman Ain',
        year: '2000',
        number: '9',
        title: 'Punishment for Rape',
        chapter: 'II',
        chapterTitle: 'Offences and Penalties',
        previewText: 'If any man commits rape upon a woman or child, he shall be punished with death, or imprisonment for life...',
        fullText: 'If any man commits rape upon a woman or child, he shall be punished with death, or imprisonment for life, and shall also be liable to fine.',
        subsections: [],
        relatedSections: ['10', '11'],
    },
    {
        actName: 'The Limitation Act',
        year: '1908',
        number: '3',
        title: 'Dismissal of suits, etc., instituted, etc., after period of limitation',
        chapter: 'II',
        chapterTitle: 'Limitation of Suits, Appeals and Applications',
        previewText: 'Subject to the provisions contained in sections 4 to 25 (inclusive), every suit instituted, appeal preferred, and application made after the period of limitation...',
        fullText: 'Subject to the provisions contained in sections 4 to 25 (inclusive), every suit instituted, appeal preferred, and application made after the period of limitation prescribed therefor by the first schedule shall be dismissed, although limitation has not been set up as a defence.',
        subsections: [],
        relatedSections: ['4', '5'],
    },
    {
        actName: 'The General Clauses Act',
        year: '1897',
        number: '3',
        title: 'Definitions',
        chapter: 'I',
        chapterTitle: 'Preliminary',
        previewText: 'In this Act, and in all General Acts and Regulations made after the commencement of this Act, unless there is anything repugnant in the subject or context...',
        fullText: '“Document” shall include any matter written, expressed or described upon any substance by means of letters, figures or marks, or by more than one of those means which is intended to be used, or which may be used, for the purpose of recording that matter.',
        subsections: [],
    },
    {
        actName: 'The Penal Code',
        year: '1860',
        number: '34',
        title: 'Acts done by several persons in furtherance of common intention',
        chapter: 'II',
        chapterTitle: 'General Explanations',
        previewText: 'When a criminal act is done by several persons, in furtherance of the common intention of all, each of such persons is liable...',
        fullText: 'When a criminal act is done by several persons, in furtherance of the common intention of all, each of such persons is liable for that act in the same manner as if it were done by him alone.',
        subsections: [],
        relatedSections: ['35', '37', '38'],
    },
    {
        actName: 'The Penal Code',
        year: '1860',
        number: '141',
        title: 'Unlawful assembly',
        chapter: 'VIII',
        chapterTitle: 'Of Offences against the Public Tranquillity',
        previewText: 'An assembly of five or more persons is designated an "unlawful assembly", if the common object of the persons comprising that assembly is...',
        fullText: 'An assembly of five or more persons is designated an "unlawful assembly", if the common object of the persons comprising that assembly is— First — To overawe by criminal force, or show of criminal force, the Government or any public servant in the exercise of the lawful power of such public servant; or Second — To resist the execution of any law, or of any legal process; or Third — To commit any mischief or criminal trespass, or other offence...',
        subsections: ['Common object', 'Five or more persons', 'Resistance to law'],
        relatedSections: ['142', '143', '149'],
    },
    {
        actName: 'The Penal Code',
        year: '1860',
        number: '149',
        title: 'Every member of unlawful assembly guilty of offence committed in prosecution of common object',
        chapter: 'VIII',
        chapterTitle: 'Of Offences against the Public Tranquillity',
        previewText: 'If an offence is committed by any member of an unlawful assembly in prosecution of the common object of that assembly...',
        fullText: 'If an offence is committed by any member of an unlawful assembly in prosecution of the common object of that assembly, or such as the members of that assembly knew to be likely to be committed in prosecution of that object, every person who, at the time of the committing of that offence, is a member of the same assembly, is guilty of that offence.',
        subsections: [],
        relatedSections: ['141', '143'],
    },
    {
        actName: 'The Penal Code',
        year: '1860',
        number: '124A',
        title: 'Sedition',
        chapter: 'VI',
        chapterTitle: 'Of Offences against the State',
        previewText: 'Whoever by words, either spoken or written, or by signs, or by visible representation, or otherwise, brings or attempts to bring into hatred or contempt...',
        fullText: 'Whoever by words, either spoken or written, or by signs, or by visible representation, or otherwise, brings or attempts to bring into hatred or contempt, or excites or attempts to excite disaffection towards the Government established by law shall be punished with imprisonment for life or any shorter term, to which fine may be added, or with imprisonment which may extend to three years, to which fine may be added, or with fine.',
        subsections: [],
        relatedSections: [],
    },
    {
        actName: 'The Penal Code',
        year: '1860',
        number: '307',
        title: 'Attempt to murder',
        chapter: 'XVI',
        chapterTitle: 'Of Offences Affecting the Human Body',
        previewText: 'Whoever does any act with such intention or knowledge, and under such circumstances that, if he by that act caused death...',
        fullText: 'Whoever does any act with such intention or knowledge, and under such circumstances that, if he by that act caused death, he would be guilty of murder, shall be punished with imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine; and, if hurt is caused to any person by such act, the offender shall be liable either to imprisonment for life, or to such punishment as is hereinbefore mentioned.',
        subsections: [],
        relatedSections: ['300', '302'],
    },
    {
        actName: 'The Penal Code',
        year: '1860',
        number: '326',
        title: 'Voluntarily causing grievous hurt by dangerous weapons or means',
        chapter: 'XVI',
        chapterTitle: 'Of Offences Affecting the Human Body',
        previewText: 'Whoever, except in the case provided for by section 335, voluntarily causes grievous hurt by means of any instrument for shooting, stabbing or cutting...',
        fullText: 'Whoever, except in the case provided for by section 335, voluntarily causes grievous hurt by means of any instrument for shooting, stabbing or cutting, or any instrument which, used as a weapon of offence, is likely to cause death... shall be punished with imprisonment for life, or with imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine.',
        subsections: [],
        relatedSections: ['320', '325'],
    },
    {
        actName: 'The Code of Criminal Procedure',
        year: '1898',
        number: '107',
        title: 'Security for keeping the peace in other cases',
        chapter: 'VIII',
        chapterTitle: 'Of Security for Keeping the Peace and for Good Behaviour',
        previewText: 'Whenever a District Magistrate or any other Executive Magistrate is informed that any person is likely to commit a breach of the peace...',
        fullText: 'Whenever a District Magistrate or any other Executive Magistrate is informed that any person is likely to commit a breach of the peace or disturb the public tranquillity, or to do any wrongful act that may probably occasion a breach of the peace, or disturb the public tranquillity, the Magistrate may require such person to show cause why he should not be ordered to execute a bond, with or without sureties, for keeping the peace for such period not exceeding one year as the Magistrate thinks fit to fix.',
        subsections: [],
        relatedSections: ['108', '110'],
    },
    {
        actName: 'The Code of Criminal Procedure',
        year: '1898',
        number: '161',
        title: 'Examination of witnesses by police',
        chapter: 'XIV',
        chapterTitle: 'Information to the Police and Their Powers to Investigate',
        previewText: 'Any police-officer making an investigation under this Chapter or any police-officer not below such rank as the Government may, by general or special order...',
        fullText: '(1) Any police-officer making an investigation... may examine orally any person supposed to be acquainted with the facts and circumstances of the case.\n(2) Such person shall be bound to answer all questions relating to such case put to him by such officer, other than questions the answers to which would have a tendency to expose him to a criminal charge or to a penalty or forfeiture.',
        subsections: ['Oral examination', 'Obligation to answer', 'Exceptions'],
        relatedSections: ['162'],
    },
    {
        actName: 'The Code of Criminal Procedure',
        year: '1898',
        number: '164',
        title: 'Power to record statements and confessions',
        chapter: 'XIV',
        chapterTitle: 'Information to the Police and Their Powers to Investigate',
        previewText: 'Any Metropolitan Magistrate, any judicial Magistrate of the first class, or any judicial Magistrate of the second class specially empowered...',
        fullText: 'Any Metropolitan Magistrate, any judicial Magistrate of the first class, or any judicial Magistrate of the second class specially empowered... may, if he is not a police-officer, record any statement or confession made to him in the course of an investigation under this Chapter or at any time afterwards before the commencement of the inquiry or trial.',
        subsections: ['Confession recording', 'Voluntary nature', 'Warning by Magistrate'],
        relatedSections: ['364'],
    },
    {
        actName: 'The Code of Criminal Procedure',
        year: '1898',
        number: '497',
        title: 'When bail may be taken in case of non-bailable offence',
        chapter: 'XXXIX',
        chapterTitle: 'Of Bail',
        previewText: 'When any person accused of any non-bailable offence is arrested or detained without warrant by an officer in charge of a police-station...',
        fullText: 'When any person accused of any non-bailable offence is arrested or detained without warrant... he may be released on bail, but he shall not be so released if there appear reasonable grounds for believing that he has been guilty of an offence punishable with death or with imprisonment for life.',
        subsections: ['Bail discretion', 'Exemptions for sick, women, children'],
        relatedSections: ['496', '498'],
    },
    {
        actName: 'The Code of Criminal Procedure',
        year: '1898',
        number: '561A',
        title: 'Saving of inherent power of High Court Division',
        chapter: 'XLVI',
        chapterTitle: 'Miscellaneous',
        previewText: 'Nothing in this Code shall be deemed to limit or affect the inherent power of the High Court Division to make such orders as may be necessary...',
        fullText: 'Nothing in this Code shall be deemed to limit or affect the inherent power of the High Court Division to make such orders as may be necessary to give effect to any order under this Code, or to prevent abuse of the process of any Court or otherwise to secure the ends of justice.',
        subsections: [],
        relatedSections: [],
    },
    {
        actName: 'The Code of Civil Procedure',
        year: '1908',
        number: '96',
        title: 'Appeal from original decree',
        chapter: 'VII',
        chapterTitle: 'Appeals from Original Decrees',
        previewText: 'Save where otherwise expressly provided in the body of this Code or by any other law for the time being in force, an appeal shall lie...',
        fullText: 'Save where otherwise expressly provided... an appeal shall lie from every decree passed by any Court exercising original jurisdiction to the Court authorized to hear appeals from the decisions of such Court.',
        subsections: [],
        relatedSections: ['97', '100'],
    },
    {
        actName: 'The Code of Civil Procedure',
        year: '1908',
        number: '115',
        title: 'Revision',
        chapter: 'VIII',
        chapterTitle: 'Reference, Review and Revision',
        previewText: 'The High Court Division may call for the record of any case which has been decided by any Court subordinate to it...',
        fullText: 'The High Court Division may call for the record of any case which has been decided by any Court subordinate to it and in which no appeal lies thereto, and if such subordinate Court appears— (a) to have exercised a jurisdiction not vested in it by law, or (b) to have failed to exercise a jurisdiction so vested...',
        subsections: [],
        relatedSections: ['113', '114'],
    },
    {
        actName: 'The Code of Civil Procedure',
        year: '1908',
        number: 'Order 39, Rule 1',
        title: 'Cases in which temporary injunction may be granted',
        chapter: 'Order XXXIX',
        chapterTitle: 'Temporary Injunctions and Interlocutory Orders',
        previewText: 'Where in any suit it is proved by affidavit or otherwise— (a) that any property in dispute in a suit is in danger of being wasted, damaged or alienated...',
        fullText: 'Where in any suit it is proved by affidavit or otherwise— (a) that any property in dispute in a suit is in danger of being wasted, damaged or alienated by any party to the suit, or wrongfully sold in execution of a decree, or (b) that the defendant threatens, or intends, to remove or dispose of his property with a view to defrauding his creditors...',
        subsections: [],
        relatedSections: ['Order 39, Rule 2'],
    },
    {
        actName: 'The Contract Act',
        year: '1872',
        number: '23',
        title: 'What considerations and objects are lawful and what not',
        chapter: 'II',
        chapterTitle: 'Of Contracts, Voidable Contracts and Void Agreements',
        previewText: 'The consideration or object of an agreement is lawful, unless— it is forbidden by law; or is of such a nature that, if permitted, it would defeat the provisions of any law...',
        fullText: 'The consideration or object of an agreement is lawful, unless— it is forbidden by law; or is of such a nature that, if permitted, it would defeat the provisions of any law; or is fraudulent; or involves or implies injury to the person or property of another; or the Court regards it as immoral, or opposed to public policy.',
        subsections: [],
        relatedSections: ['24', '25'],
    },
    {
        actName: 'The Contract Act',
        year: '1872',
        number: '73',
        title: 'Compensation for loss or damage caused by breach of contract',
        chapter: 'VI',
        chapterTitle: 'Of the Consequences of Breach of Contract',
        previewText: 'When a contract has been broken, the party who suffers by such breach is entitled to receive, from the party who has broken the contract...',
        fullText: 'When a contract has been broken, the party who suffers by such breach is entitled to receive, from the party who has broken the contract, compensation for any loss or damage caused to him thereby, which naturally arose in the usual course of things from such breach, or which the parties knew, when they made the contract, to be likely to result from the breach of it.',
        subsections: [],
        relatedSections: ['74', '75'],
    },
    {
        actName: 'The Evidence Act',
        year: '1872',
        number: '24',
        title: 'Confession caused by inducement, threat or promise, when irrelevant in criminal proceeding',
        chapter: 'II',
        chapterTitle: 'Of the Relevancy of Facts',
        previewText: 'A confession made by an accused person is irrelevant in a criminal proceeding, if the making of the confession appears to the Court...',
        fullText: 'A confession made by an accused person is irrelevant in a criminal proceeding, if the making of the confession appears to the Court to have been caused by any inducement, threat or promise, having reference to the charge against the accused person, proceeding from a person in authority and sufficient, in the opinion of the Court, to give the accused person grounds which would appear to him reasonable for supposing that by making it he would gain any advantage or avoid any evil of a temporal nature in reference to the proceedings against him.',
        subsections: [],
        relatedSections: ['25', '26', '27'],
    },
    {
        actName: 'The Evidence Act',
        year: '1872',
        number: '32',
        title: 'Cases in which statement of relevant fact by person who is dead or cannot be found, etc., is relevant',
        chapter: 'II',
        chapterTitle: 'Of the Relevancy of Facts',
        previewText: 'Statements, written or oral, of relevant facts made by a person who is dead, or who cannot be found, or who has become incapable of giving evidence...',
        fullText: 'Statements, written or oral, of relevant facts made by a person who is dead... are themselves relevant facts in the following cases: (1) When the statement is made by a person as to the cause of his death, or as to any of the circumstances of the transaction which resulted in his death, in cases in which the cause of that person\'s death comes into question.',
        subsections: ['Dying declaration', 'Statement made in course of business'],
        relatedSections: ['33'],
    },
    {
        actName: 'The Transfer of Property Act',
        year: '1882',
        number: '105',
        title: 'Lease defined',
        chapter: 'V',
        chapterTitle: 'Of Leases of Immoveable Property',
        previewText: 'A lease of immoveable property is a transfer of a right to enjoy such property, made for a certain time, express or implied, or in perpetuity...',
        fullText: 'A lease of immoveable property is a transfer of a right to enjoy such property, made for a certain time, express or implied, or in perpetuity, in consideration of a price paid or promised, or of money, a share of crops, service or any other thing of value, to be rendered periodically or on specified occasions to the transferor by the transferee, who accepts the transfer on such terms.',
        subsections: ['Lessor', 'Lessee', 'Premium', 'Rent'],
        relatedSections: ['106', '107'],
    },
    {
        actName: 'The Transfer of Property Act',
        year: '1882',
        number: '58',
        title: '“Mortgage” defined',
        chapter: 'IV',
        chapterTitle: 'Of Mortgages of Immoveable Property and Charges',
        previewText: 'A mortgage is the transfer of an interest in specific immoveable property for the purpose of securing the payment of money advanced...',
        fullText: 'A mortgage is the transfer of an interest in specific immoveable property for the purpose of securing the payment of money advanced or to be advanced by way of loan, an existing or future debt, or the performance of an engagement which may give rise to a pecuniary liability.',
        subsections: ['Simple mortgage', 'Mortgage by conditional sale', 'Usufructuary mortgage', 'English mortgage'],
        relatedSections: ['59', '60'],
    },
    {
        actName: 'The Limitation Act',
        year: '1908',
        number: '5',
        title: 'Extension of period in certain cases',
        chapter: 'II',
        chapterTitle: 'Limitation of Suits, Appeals and Applications',
        previewText: 'Any appeal or application for a review of judgment or for leave to appeal or any other application to which this section may be made applicable...',
        fullText: 'Any appeal or application for a review of judgment or for leave to appeal or any other application... may be admitted after the period of limitation prescribed therefor, when the appellant or applicant satisfies the Court that he had sufficient cause for not preferring the appeal or making the application within such period.',
        subsections: ['Sufficient cause'],
        relatedSections: ['3'],
    },
    {
        actName: 'The Nari-O-Shishu Nirjatan Daman Ain',
        year: '2000',
        number: '11',
        title: 'Punishment for causing death, etc., for dowry',
        chapter: 'II',
        chapterTitle: 'Offences and Penalties',
        previewText: 'If the husband of a woman or the father, mother, guardian, relative or any other person on the side of the husband causes death...',
        fullText: 'If the husband of a woman or the father, mother, guardian, relative or any other person on the side of the husband causes death or attempts to cause death of a woman for dowry, he shall be punished with death or imprisonment for life and shall also be liable to fine.',
        subsections: [],
        relatedSections: ['2', '9'],
    },
    {
        actName: 'Cyber Security Act',
        year: '2023',
        number: '25',
        title: 'Punishment for publishing or broadcasting offensive, false or fear inducing information',
        chapter: 'V',
        chapterTitle: 'Offences and Penalties',
        previewText: 'If any person through a website or any other electronic format deliberately or knowingly publishes or broadcasts any information which is offensive or false...',
        fullText: 'If any person through a website or any other electronic format deliberately or knowingly publishes or broadcasts any information which is offensive or false to annoy, insult, humiliate or malign a person... he shall be punishable with imprisonment for a term not exceeding 2 years or with fine not exceeding 3 lac taka or with both.',
        subsections: [],
        relatedSections: [],
    },
    {
        actName: 'The Labor Act',
        year: '2006',
        number: '3',
        title: 'Conditions of employment',
        chapter: 'II',
        chapterTitle: 'Conditions of Service and Employment',
        previewText: 'In every establishment, the conditions of employment and other matters shall be as specified in this Chapter...',
        fullText: 'In every establishment, the conditions of employment and other matters relating to service shall be as specified in this Chapter: Provided that any establishment may have its own service rules, but no such rules shall be less favourable to any worker than the provisions of this Chapter.',
        subsections: [],
        relatedSections: ['4', '5'],
    },
    {
        actName: 'The Labor Act',
        year: '2006',
        number: '18',
        title: 'Procedure for punishment',
        chapter: 'II',
        chapterTitle: 'Conditions of Service and Employment',
        previewText: 'No order of punishment under section 17 shall be made against a worker unless— (a) the allegations against him are recorded in writing...',
        fullText: 'No order of punishment under section 17 shall be made against a worker unless— (a) the allegations against him are recorded in writing; (b) he is given a copy thereof and not less than seven days\' time to explain; (c) he is given an opportunity of being heard...',
        subsections: ['Show cause notice', 'Enquiry procedure'],
        relatedSections: ['17'],
    },
    {
        actName: 'Muslim Marriages and Divorces (Registration) Act',
        year: '1974',
        number: '3',
        title: 'Registration of marriages',
        chapter: 'I',
        chapterTitle: 'Preliminary',
        previewText: 'Notwithstanding anything contained in any law, custom or usage, every marriage solemnized between Muslims shall be registered...',
        fullText: 'Notwithstanding anything contained in any law, custom or usage, every marriage solemnized between Muslims shall be registered in accordance with the provisions of this Act.',
        subsections: [],
        relatedSections: [],
    },
    {
        actName: 'Consumer Rights Protection Act',
        year: '2009',
        number: '37',
        title: 'Punishment for not displaying price of goods',
        chapter: 'V',
        chapterTitle: 'Offences and Penalties',
        previewText: 'If any person fails to display the price-list of goods at a visible place of his shop or business establishment...',
        fullText: 'If any person fails to display the price-list of goods at a visible place of his shop or business establishment, he shall be punished with imprisonment for a term not exceeding one year, or with fine not exceeding fifty thousand taka, or with both.',
        subsections: [],
        relatedSections: [],
    },
    {
        actName: 'The Environment Conservation Act',
        year: '1872',
        number: '4',
        title: 'Powers and functions of the Director General',
        chapter: 'I',
        chapterTitle: 'Preliminary',
        previewText: 'Subject to the provisions of this Act, the Director General may take such measures as he considers necessary or expedient...',
        fullText: 'Subject to the provisions of this Act, the Director General may take such measures as he considers necessary or expedient for the conservation of environment, improvement of environmental standards and control and abatement of pollution of environment.',
        subsections: [],
        relatedSections: [],
    },
    {
        actName: 'The Arbitration Act',
        year: '2001',
        number: '7',
        title: 'Scope of judicial intervention',
        chapter: 'I',
        chapterTitle: 'Preliminary',
        previewText: 'Notwithstanding anything contained in any other law for the time being in force, in matters governed by this Act...',
        fullText: 'Notwithstanding anything contained in any other law for the time being in force, in matters governed by this Act, no judicial authority shall intervene except as provided in this Act.',
        subsections: [],
        relatedSections: [],
    },
    {
        actName: 'The Registration Act',
        year: '1908',
        number: '17',
        title: 'Documents of which registration is compulsory',
        chapter: 'III',
        chapterTitle: 'Of Registrable Documents',
        previewText: 'The following documents shall be registered, if the property to which they relate is situate in a district in which...',
        fullText: '(1) The following documents shall be registered... (a) instruments of gift of immoveable property; (b) other non-testamentary instruments which purport or operate to create, declare, assign, limit or extinguish... any right, title or interest... to or in immoveable property.',
        subsections: ['Gift instruments', 'Sale deeds', 'Mortgage deeds'],
        relatedSections: ['18', '49'],
    },
    {
        actName: 'Wait Success Message Update',
        year: '2024',
        number: '1',
        title: 'Dummy',
        chapter: 'I',
        chapterTitle: 'Dummy',
        previewText: 'Dummy',
        fullText: 'Dummy',
        subsections: [],
        relatedSections: [],
    }
];

const seedLegalData = async () => {
    try {
        await mongoose.connect(config.database_url as string);
        console.log('Connected to database for seeding...');

        // Clear existing data (optional, but keep it for now to ensure a clean start)
        await Legal.deleteMany({});
        console.log('Cleared existing legal data.');

        await Legal.insertMany(BANGLADESHI_LAWS);
        console.log('Successfully seeded 51 Bangladeshi laws!');

        process.exit(0);
    } catch (error) {
        console.error('Error seeding data:', error);
        process.exit(1);
    }
};

seedLegalData();
